Vagrant.configure("2") do |config|
  # Define the base box
  config.vm.box = "ubuntu/jammy64" # ubuntu/lunar64

  # Provision Docker and initialize Swarm
  config.vm.provision "docker" do |d|
    d.pull_images "caddy:2.8"
  end

  # Copy Docker images to the VM
  config.vm.provision "file", source: "./public", destination: "/home/vagrant/site"

  # Provision Docker Swarm and load Docker images
  config.vm.provision "shell", inline: <<-SHELL
    # Install required tools
    apt-get update -y
    apt-get install -y jq curl
    
    # Initialize Docker Swarm
    docker swarm init --advertise-addr $(hostname -I | awk '{print $2}')

    # Load the transferred Docker image
    docker load < /home/vagrant/site/prod-admin.tar
    docker load < /home/vagrant/site/prod-client.tar

    # Deploy the Swarm stack
    docker stack deploy -c /home/vagrant/site/docker-compose.yml blogger
  SHELL

  config.vm.synced_folder "public/", "/home/vagrant/public"

  # Access the server locally with HTTPS
  # config.vm.network "private_network", type: "dhcp"
  config.vm.network "private_network", ip: "192.168.56.6"
end
