---
- name: 'Apache Two'
  hosts: all
  become: true

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Create password file
      shell:
        cmd: |
          htpasswd -b -c /etc/apache2/.htpasswd admin site_two_pass

    - name: Start Apache
      service:
        name: apache2
        state: started

    - name: Copy website files
      shell:
        cmd: |
          mkdir -p /var/www/html/example.com
          cp -R /vagrant/public/mediplus/* /var/www/html/example.com
          cp /vagrant/public/login_two.html /var/www/html/example.com/login.html
          cp /vagrant/app.conf /etc/apache2/sites-available/example.com.conf

    - name: Enable Modules
      shell:
        cmd: |
          a2enmod session
          a2enmod session_cookie
          a2enmod session_crypto
          a2enmod auth_form
          a2enmod request

    - name: Enable new site
      shell: /usr/sbin/a2ensite example.com
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
