---
- name: 'Nginx Two'
  hosts: all
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install apache2-utils and create password file
      shell:
        cmd: |
          apt install -y apache2-utils
          htpasswd -b -c /etc/nginx/.htpasswd admin nginx_two_pass

    - name: Start Nginx
      service:
        name: nginx
        state: started

    - name: Copy Website Files
      shell:
        cmd: |
          cp -R /vagrant/public/mediplus/* /usr/share/nginx/html
          cp /vagrant/public/login_two.html /usr/share/nginx/html/login.html
          cp /vagrant/app.conf /etc/nginx/sites-available/default

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
