---
- name: 'Apache One'
  hosts: all
  become: true

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Create password file
      shell:
        cmd: |
          htpasswd -b -c /etc/apache2/.htpasswd admin site_one_pass

    - name: Start Apache
      service:
        name: apache2
        state: started

    - name: Copy website files
      shell:
        cmd: |
          mkdir -p /var/www/html/example.com
          cp -R /vagrant/public/inance/* /var/www/html/example.com
          cp /vagrant/public/login_one.html /var/www/html/example.com/login.html
          cp /vagrant/app.conf /etc/apache2/sites-available/example.com.conf

    - name: Enable website
      shell:
        cmd: |
          a2dissite 000-default.conf
          a2ensite example.com
          systemctl reload apache2

    - name: Reload Apache2
      service:
        name: apache2
        state: reloaded
