apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30001
  selector:
    app: nginx
    tier: frontend

# Run the following command to get the url of the service
# minikube service nginx-service --url

# Only needed because of the VM Setup
# To access the service url from the host machine of the VM, run the following command
# ssh -g -N -L 8080:192.168.49.2:31529 -i .vagrant/machines/default/virtualbox/private_key vagrant@192.168.56.6
# Then open the url http://localhost:8080 in the browser

# 192.168.49.2:31529 # this is the url returned by minikube service
