apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer # only works for some cloud providers
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
    tier: frontend
